== Introduction

This is a fork of the original repo.

.new features

* support adoc
* support oh-my-zsh plugin mechanism

== howto
[source,bash]
--
files=($(find ./ -type f -name '*.md'))
for item in ${files[*]}
do
    printf "   %s\n" $item
    pandoc $item --atx-headers --verbose --reference-links -t asciidoc -o ${item/.md/.adoc}
    rm $item
done
--

== ADR Tools

A command-line tool for working with a log of
http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions[Architecture
Decision Records] (ADRs).

https://travis-ci.org/zhoumingjun/adr-tools[image:https://travis-ci.org/zhoumingjun/adr-tools.svg?branch=master[Build
Status]]

=== Quick Start

link:INSTALL.adoc[Install ADR Tools].

Use the `+adr+` command to manage ADRs. Try running `+adr help+`.

ADRs are stored in a subdirectory of your project as Markdown files. The
default directory is `+doc/adr+`, but you can specify the directory when
you initialise the ADR log.

[arabic]
. Create an ADR directory in the root of your project:
+
....
 adr init doc/architecture/decisions
....
+
This will create a directory named `doc/architecture/decisions’
containing the first ADR, which records that you are using ADRs to
record architectural decisions and links to
http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions[Michael
Nygard’s article on the subject].
. Create Architecture Decision Records
+
....
 adr new Implement as Unix shell scripts
....
+
This will create a new, numbered ADR file and open it in your editor of
choice (as specified by the VISUAL or EDITOR environment variable).
+
To create a new ADR that supercedes a previous one (ADR 9, for example),
use the -s option.
+
....
 adr new -s 9 Use Rust for performance-critical functionality
....
+
This will create a new ADR file that is flagged as superceding ADR 9,
and changes the status of ADR 9 to indicate that it is superceded by the
new ADR. It then opens the new ADR in your editor of choice.
. For further information, use the built in help:
+
....
 adr help
....

See the link:tests/[tests] for detailed examples.

The decisions for this tool are recorded as link:doc/adr/[architecture
decision records in the project repository].
